### PR TITLE
Rework multiselectable - use of mousedown

### PR DESCRIPTION
**Pull request by nickelodeon**
Eight commits building towards use of mousedown rather than click as core event handler. Nice code formatting (tabbing/spacing) appears to have been lost throughout; we can reestablish this if and when the code itself is good.

### CODE REVIEW

**Comment by iamvery** [comment]
Hey man! I wanted to let you know that I haven't forgotten about you :). I've been really covered up between jobs recently. It may take some time, but I'll definitely be working on this!

**Comment by nickelodeon** [comment]
No drama, Jay. I'm a little snowed right now, too, Whenever is fine.

**Comment by Seabizkit** [comment]
- 1 want mousedown.... gd work! so far

**Comment by neochief** [comment]
Fixed in https://github.com/shvetsgroup/jquery.multisortable

**Comment by iamvery** [comment]
@neochief I realize that this project does not get a lot of attention, but I'm curious why you'd choose to fork it rather than contribute back to the existing project.

**Comment by neochief** [comment]
Main reason because I've seen that all of these issues and pull requests stay unresolved for months. I thought that you've abandoned the project. If not, I can send a nice big pull request ;)

**Comment by iamvery** [comment]
@neochief yeah that's understandable. My concern is further fragmentation of this project. I brought it into GH because it seemed to be abandoned by its creator. I'll take a look through the open issues and see if I can get them in order. Please do send a PR if you're up for it.

**Comment by neochief** [comment]
There you go: https://github.com/iamvery/jquery.multisortable/pull/11

BTW, maybe it's worth adding somebody (like me) as a project collaborator in order to help you with maintaining issues & pull requests, when you don't have time on this.

**Comment by neochief** [comment]
I'm closing this pull request since all of the issues fixed by @nickelodeon are now fixed as well in main repo (although, some of them are fixed in different way). It would be great if you could test the new code in your project and see if there are anything which I missed. Thanks!

**Pull request closed without merging**
