### PR TITLE
Merge with shvetsgroup/jquery.multisortable

### PR DESCRIPTION
**Pull request by neochief**
This version contains all the fixes I've found in different forks of iamvery/jquery.multisortable. It's hard to recall all of them, but you can be sure that they have made sense ;)

In addition to that:
- Improved Shift-selecting so that it works more like in Finder/Explorer.
- The unit tests were updated and fixed.
- Added Travis CI configuration (in last commit I've changed the account to "iamvery", so you should make sure you've enabled Travis integration with your repository).
- Tuned paths.
- Fixed README.

### CODE REVIEW

**Comment by iamvery** [comment]
Wow, that is the pull request to end all pull requests! :tongue:

I've done a lot of thinking about this, and I think I should just wash my hands of this. I believe I felt a little attachment to the project because I felt like I took on some responsibility by mirroring it from another person w/o explicit permission. If you're OK w/ it, I'll just transfer ownership of the repository to you and let you pave the way forward. I will of course link to your repo as the "official" location.

How does that sound to you?

**Comment by neochief** [comment]
Hey Jay, sorry for the very late response. Thank you very much, I surely didn't expect that. I promise to keep the project nice and sound. Thanks again.

**Comment by iamvery** [comment]
@neochief I initiated the transfer of ownership. I'm not sure how it will react since you already have a repo by this name, but we'll see... Honestly it may make for since for us to just leave this repo under my user, clear it out, and point the readme to your fork. I'm cool either way.

**Comment by neochief** [comment]
Okay, it worked perfectly, I merged changes from the fork back to this repo, then removed fork and transferred repo to the organization account (shvetsgroup). Now all the traffic from google goes straight to the correct destination. 

And again, thanks for all your work, Jay!

**Comment by iamvery** [comment]
Excellent! :+1:

**Pull request closed without merging**
